version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pricewatcher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pricewatcher
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TWILIO_ACCOUNT_SID: dummy
      TWILIO_AUTH_TOKEN: dummy
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata: